name: Run C++ Minifier Python Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-minifier:
    runs-on: ubuntu-latest
    steps:
        #4.2.2 or else it throws random warnings
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        #required to be 2.7 for compat reasons
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '2.7' 

      - name: Download minifier script
        run: |
          curl -sSL https://githubusercontent.com -o minifier.py
          
      - name: Convert script to Python 3
        # github removed python2 (for reasonable reasons, as annoying as it is.) this is a translator thats needed so we can run this.
        run: |
          python -m docutils 2>/dev/null || true
          2to3 -w minifier.py

      - name: Run python script
        run: python minifier.py fraction.h > fraction.min.h

      - name: Save minified file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minified-header-file
          path: fraction.min.h
