name: Run C++ Minifier Python Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-minifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Download minifier script
        run: |
          curl -sSL https://githubusercontent.com -o minifier.py

      - name: Run python script
        run: python minifier.py fraction.h > fraction.min.h

      - name: Save minified file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minified-header-file
          path: fraction.min.h
